### PR TITLE
Update for PHP 7.2 or later

### PR DESCRIPTION
**Pull request by kenjis**
Supersedes #63 

- Update dependencies
  - Update to PHPUnit 8.5
- Add GitHub Actions workflow to run PHPUnit
- Add `composer test` and `composer coverage`

### CODE REVIEW

**Comment by kenjis** [comment]
Why does not Github Actions work?

**Comment by kenjis** [comment]
@harikt Can you have a look?

**Comment by harikt** [comment]
@kenjis github actions were not set. I did it now.

**Comment by kenjis** [comment]
@harikt Thanks!

**Pull request merged**
